### ISSUE TITLE
[바론] 03월 02주차

### ISSUE THREAD

**Issue by somsom13** [woowacourse-study/2023-gb-code#10]
## Todo
- [x] 1장 코드 품질 읽기
- [x] 1장 코드 품질 정리
- [x] 2장 추상화 계층 읽기
- [x] 2장 추상화 계층 정리
