### ISSUE TITLE
[조이] 03월 03주차

### ISSUE THREAD

**Issue by yeonkkk** [woowacourse-study/2023-gb-code#13]
## Todo
- [ ] 4장 오류 읽기
- [ ] 4장 오류 정리
- [ ] 5장 가독성 높은 코드를 작성하라 읽기
- [ ] 5장 가독성 높은 코드를 작성하라 정리
- [ ] 6장 예측 가능한 코드를 작성하라 읽기
- [ ] 6장 예측 가능한 코드를 작성하라 정리

**Comment by yeonkkk** [comment]
3월 3주차는 바빠서 책을 못 읽었습니다.. 이슈 닫고 4주차에 진행하겠습니다!🥲
