### ISSUE TITLE
[조이] 04월 03주차

### ISSUE THREAD

**Issue by yeonkkk** [woowacourse-study/2023-gb-code#21]
## Todo
- [x] [SQL 첫걸음] 3강 읽기, 정리
- [x] [SQL 첫걸음] 4강 읽기, 정리
- [x] [SQL 첫걸음] 5강 읽기, 정리
- [x] [SQL 첫걸음] 6강 읽기, 정리
- [x] [SQL 첫걸음] 7강 읽기, 정리
- [x] [SQL 첫걸음] 8강 읽기, 정리
