### ISSUE TITLE
[제이미] 04월 02주차

### ISSUE THREAD

**Issue by JJ503** [woowacourse-study/2023-gb-code#22]
## Todo
- [ ] [SQL 첫걸음] 1강 읽기 및 정리
- [ ] [SQL 첫걸음] 2강 읽기 및 정리
- [ ] [SQL 첫걸음] 3강 읽기 및 정리
