### ISSUE TITLE
[제이미] 04월 03주차

### ISSUE THREAD

**Issue by JJ503** [woowacourse-study/2023-gb-code#23]
## Todo
- [x] [SQL 첫걸음] 4강 읽기 및 정리
- [x] [SQL 첫걸음] 5강 읽기 및 정리
- [x] [SQL 첫걸음] 6강 읽기 및 정리
- [x] [SQL 첫걸음] 7강 읽기 및 정리
- [x] [SQL 첫걸음] 8강 읽기 및 정리
- [x] [SQL 첫걸음] 9강 읽기 및 정리
- [x] [SQL 첫걸음] 10강 읽기 및 정리
