### ISSUE TITLE
[바론] 04월 03주차

### ISSUE THREAD

**Issue by somsom13** [woowacourse-study/2023-gb-code#25]
## Todo
- [x] SQL 첫걸음 3장 읽고 정리
- [x] SQL 첫걸음 4장 읽고 정리
- [x] SQL 첫걸음 5장 읽고 정리
- [x] SQL 첫걸음 6장 읽고 정리
- [x] SQL 첫걸음 7장 읽고 정리
- [x] SQL 첫걸음 8장 읽고 정리 -> 가능하면....^^
