### ISSUE TITLE
[제이미] 04월 04주차

### ISSUE THREAD

**Issue by JJ503** [woowacourse-study/2023-gb-code#29]
## Todo
- [x] [SQL 첫걸음] 11강 읽기 및 정리
- [x] [SQL 첫걸음] 12강 읽기 및 정리
- [ ] [SQL 첫걸음] 13강 읽기 및 정리
- [ ] [SQL 첫걸음] 14강 읽기 및 정리
- [ ] [SQL 첫걸음] 15강 읽기 및 정리
- [ ] [SQL 첫걸음] 16강 읽기 및 정리
- [ ] [SQL 첫걸음] 17강 읽기 및 정리
