### ISSUE TITLE
[조이] 04월 04주차

### ISSUE THREAD

**Issue by yeonkkk** [woowacourse-study/2023-gb-code#30]
## Todo
- [ ] [SQL 첫걸음] 9강 읽기 및 정리
- [ ] [SQL 첫걸음] 10강 읽기 및 정리
- [ ] [SQL 첫걸음] 11강 읽기 및 정리
- [ ] [SQL 첫걸음] 12강 읽기 및 정리
- [ ] [SQL 첫걸음] 13강 읽기 및 정리
- [ ] [SQL 첫걸음] 14강 읽기 및 정리
- [ ] [SQL 첫걸음] 15강 읽기 및 정리
- [ ] [SQL 첫걸음] 16강 읽기 및 정리
- [ ] [SQL 첫걸음] 17강 읽기 및 정리
- [ ] [SQL 첫걸음] 18강 읽기 및 정리
- [ ] [SQL 첫걸음] 19강 읽기 및 정리
