### ISSUE TITLE
[바론] 05월 02주차

### ISSUE THREAD

**Issue by somsom13** [woowacourse-study/2023-gb-code#31]
## Todo
- [x] [SQL 첫걸음] 9장 읽고 정리
- [x] [SQL 첫걸음] 10장 읽고 정리
- [x] [SQL 첫걸음] 11장 읽고 정리
- [x] [SQL 첫걸음] 12장 읽고 정리
- [x] [SQL 첫걸음] 13장 읽고 정리
- [x] [SQL 첫걸음] 14장 읽고 정리
- [x] [SQL 첫걸음] 15장 읽고 정리
