### ISSUE TITLE
[제이미] 3월 1주차

### ISSUE THREAD

**Issue by JJ503** [woowacourse-study/2023-gb-code#5]
## Todo
- [x] 1장 코드 품질 읽기
- [x] 1장 코드 품질 정리
- [x] 2장 추상화 계층 읽기

**Comment by JJ503** [comment]
2장 추상화 계층 읽기까지는 완료했는데 정리할 힘이 없어 몰래 빼버렸습니다ㅎㅎ
2주 차에 함께 정리하도록 하겠습니다..!
