### ISSUE TITLE
[조이] 03월 02주차

### ISSUE THREAD

**Issue by yeonkkk** [woowacourse-study/2023-gb-code#8]
## Todo
- [x] 2장 추상화 계층 읽기
- [x] 2장 추상화 계층 정리
- [x] 3장 다른 개발자와 코드 계약 읽기
- [x] 3장 다른 개발자와 코드 계약 정리
