### ISSUE TITLE
[제이미] 03월 02주차

### ISSUE THREAD

**Issue by JJ503** [woowacourse-study/2023-gb-code#9]
## Todo
- [ ] 2장 추상화 계층 정리
- [ ] 3장 다른 개발자와 코드 계약 읽기
- [ ] 3장 다른 개발자와 코드 계약 정리
- [ ] 4장 오류 읽기
- [ ] 4장 오류 정리

**Comment by JJ503** [comment]
늦어져 죄송합니다.
2주차에 대한 pr 화요일까지는 올릴 수 있도록 하겠습니다..!

**Comment by yeonkkk** [comment]
레벨 1 종료로 이슈 전체 마감합니다:)
